name: Deploy Uptime Kuma to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            cd ~/uptime-kuma || (mkdir ~/uptime-kuma && cd ~/uptime-kuma)
            rm -f docker-compose.yml
            curl -O https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.yml
            docker compose pull
            docker compose up -d
