name: Deploy Uptime Kuma to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Déployer Uptime Kuma (docker compose)
        run: |
          cd ~/projet-ecf/uptime-kuma-cicd
          docker compose pull
          docker compose up -d

